export const LOCATION_CITY_NAME = 'LOCATION_CITY_NAME'
export const NOW_WEATHER_DATA = 'NOW_WEATHER_DATA'
export const FORECAST_WEATHER_DATA = 'FORECAST_WEATHER_DATA'
export const SEARCH_CITY_NAME = 'SEARCH_CITY_NAME'